-- MySQL Script generated by MySQL Workbench
-- Thu Mar 24 18:39:40 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Examen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Examen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Examen` DEFAULT CHARACTER SET utf8 ;
USE `Examen` ;

-- -----------------------------------------------------
-- Table `Examen`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen`.`Productos` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Codigo` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `Precio` DECIMAL(18,2) NULL,
  `Existencia` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen`.`Pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen`.`Pedidos` (
  `Codigo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Examen`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Examen`.`Usuarios` (
  `CodigoUsuarios` VARCHAR(15) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Clave` VARCHAR(45) NULL,
  PRIMARY KEY (`CodigoUsuarios`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
